import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import './globals.css';
// COMPONENTS
import { ReactQueryProvider } from '@/app/components/ReactQueryProvider';
import { ThemeProvider } from '@/app/components/ThemeProvider';

import Navigation from '@/app/components/Navigation';

const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`width-full bg-contrast text-primary antialiased dark:bg-primary ${urbanist.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navigation />
          <ReactQueryProvider>
            <div className="mx-auto max-w-[900px] px-6 pb-24 pt-16 md:px-6 md:pb-44 md:pt-20">
              {children}
            </div>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
